name: ci-check-pr
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - master
    types: [ opened, synchronize, reopened ]

jobs:
  pr-file-changes:
    runs-on: ubuntu-latest
    outputs:
      trigger-rust: ${{ steps.changed-files-yaml.outputs.rust_any_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Check changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            rust:
              - '**/*.rs'
              - '**/Cargo.toml'
              - Cargo.toml
              - Cargo.lock
      - name: Run step if doc file(s) change
        if: steps.changed-files-yaml.outputs.rust_any_changed == 'true'
        env:
          RUST_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.rust_all_changed_files }}
        run: |
          echo "One or more doc file(s) has changed."
          echo "List all the files that have changed: $RUST_ALL_CHANGED_FILES"

  ci-check-common:
    name: ci-check-common
    uses: ./.github/workflows/ci-check-common.yml

  ci-check-rust:
    name: ci-check-rust
    needs: pr-file-changes
    if: ${{ needs.pr-file-changes.outputs.trigger-rust == 'true' }}
    uses: ./.github/workflows/ci-check-rust.yml

  finalize-pr:
    runs-on: ubuntu-latest
    needs:
      - ci-check-common
      - ci-check-rust
    if: always()
    steps:
      - name: Everything is fine
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0

      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
