name: ci-check-common
on:
  workflow_call:
    inputs:
      commits-from:
        description: 'Lower end of the commit range to check'
        required: true
        default: 'HEAD~1'
        type: string
      commits-to:
        description: 'Upper end of the commit range to check'
        required: true
        default: 'HEAD'
        type: string

jobs:
  check-commit-message:
    name: commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: taiki-e/install-action@v2
        with:
          tool: commitlint-rs
      - run: commitlint --from ${{ github.event.inputs.commits-from }} --to ${{ github.event.inputs.commits-to }}
