name: ci-check-common
on:
  workflow_call:
    inputs:
      commits-from:
        description: 'Lower end of the commit range to check'
        required: true
        default: HEAD~1
        type: string
      commits-to:
        description: 'Upper end of the commit range to check'
        required: true
        default: HEAD
        type: string

jobs:
  check-commit-message:
    name: commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install convco
        uses: taiki-e/install-action@v2
        with:
          tool: convco
      - name: Print commit range to check
        run: |
          echo "Checking commit range from ${{ inputs.commits-from }} to ${{ inputs.commits-to }}"
      - name: Check commit messages
        run: |
          command -v convco
          convco --version
          git log ${{ inputs.commits-from }}..${{ inputs.commits-to }}
          convco check ${{ inputs.commits-from }}..${{ inputs.commits-to }}
