name: ci-test-rust-optional
on:
  workflow_dispatch:
  workflow_call:

env:
  CRATE_NAME: iggy
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  IGGY_CI_BUILD: true

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: "coverage"
      - name: Install gnome-keyring and keyutils on Linux
        run: |
          sudo apt-get update --yes && sudo apt-get install --yes gnome-keyring keyutils lcov
          rm -f $HOME/.local/share/keyrings/*
          echo -n "test" | gnome-keyring-daemon --unlock
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - name: Build
        run: source <(cargo llvm-cov show-env --export-prefix) && cargo build
      - name: Test
        run: source <(cargo llvm-cov show-env --export-prefix) && cargo test
      - name: Generate code coverage
        run: source <(cargo llvm-cov show-env --export-prefix) && cargo llvm-cov report --lcov --output-path coverage.lcov --ignore-filename-regex '(bench\/|integration\/|tools\/|tpc\/)'
      - name: Display code coverage
        run: lcov --summary coverage.lcov
      - name: Upload code to Coveralls
        # Do not upload coverage for user triggered workflows
        if: github.event_name == 'workflow_call'
        uses: coverallsapp/github-action@v2
        with:
          fail-on-error: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

  aarch64-apple-darwin:
    name: aarch64-apple-darwin
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: "aarch64-apple-darwin"
      - name: Prepare aarch64-apple-darwin toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: aarch64-apple-darwin
      - name: Build binary
        run: cargo build --target aarch64-apple-darwin
      - name: Run tests
        run: cargo test --target aarch64-apple-darwin
      - name: Check if workspace is clean
        run: git status | grep "working tree clean" || { git status ; exit 1; }
