name: ci-test-rust-optional

on:
  workflow_dispatch:
  workflow_call:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  IGGY_CI_BUILD: true

jobs:
  ci-coverage-rust:
    name: ci-coverage-rust
    uses: ./.github/workflows/ci-coverage-rust.yml

  aarch64-apple-darwin:
    name: aarch64-apple-darwin
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: "aarch64-apple-darwin"
      - name: Prepare aarch64-apple-darwin toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: aarch64-apple-darwin
      - name: Set verbose flag
        shell: bash
        run: echo "VERBOSE_FLAG=$([[ "${RUNNER_DEBUG}" = "1" ]] && echo "--verbose" || echo "")" >> $GITHUB_ENV
      - name: Build binary
        run: cargo build ${{ env.VERBOSE_FLAG }} --target aarch64-apple-darwin
      - name: Run tests
        run: cargo test ${{ env.VERBOSE_FLAG }} --target aarch64-apple-darwin
      - name: Check if workspace is clean
        run: git status | grep "working tree clean" || { git status ; exit 1; }
