name: ci-test-rust
on:
  workflow_dispatch:
  workflow_call:

jobs:
  x86_64-unknown-linux-musl:
    name: x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: "x86_64-unknown-linux-musl"
      - name: Install musl-tools, gnome-keyring and keyutils
        run: |
          sudo apt-get update --yes && sudo apt-get install --yes musl-tools gnome-keyring keyutils
          rm -f $HOME/.local/share/keyrings/*
          echo -n "test" | gnome-keyring-daemon --unlock
      - name: Prepare x86_64-unknown-linux-musl toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl
      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Build binary x86_64-unknown-linux-musl
        run: cross +stable build --target x86_64-unknown-linux-musl
      - name: Run tests x86_64-unknown-linux-musl
        run: cross +stable test --target x86_64-unknown-linux-musl
      - name: Check CLI examples from README
        run: ./scripts/run-examples-from-readme.sh
      - name: Check if workspace is clean
        run: git status | grep "working tree clean" || { git status ; exit 1; }

  x86_64-pc-windows-msvc:
    name: x86_64-pc-windows-msvc
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: "x86_64-pc-windows-msvc"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-msvc
      - name: Build iggy package
        run: cargo build --target x86_64-pc-windows-msvc -p iggy
      - name: Build iggy-cli binary
        run: cargo build --verbose --target x86_64-pc-windows-msvc --bin iggy
